### ISSUE TITLE
Fit button and fitters drop-down menu never get enabled.

### ISSUE THREAD

**Issue by ibusko** [nmearl/specviz#112]
Lines 72-73 in viewer.py get executed, but the actual widgets do not change on screen. They remain disabled.

Could this be a side effect of a re-arranging of the layout managers, or something in those lines?

**Comment by nmearl** [comment]
I switch from disabling just the individual button/dropdown to disabling the entire fitting routine group, but forget to wire it up that way.

Fixed in 209d2a8eb0751d1ef69241ea39fc99d862a85228.
