### ISSUE TITLE
Exception when fitting or updating model.

### ISSUE THREAD

**Issue by ibusko** [nmearl/specviz#113]
A ValueError("Unknown keyword in event emit arguments.") exception is raised due to an apparent  conflict in the 'emit' method  keywords. 

This method is called many times with different types of keyword arguments; it only fails when called from the model update calculation.

**Comment by nmearl** [comment]
Fixed in 747b003d9be09e4ce5905c0cf766d1f52f31715f. Let me know if you still see an issue.

**Comment by ibusko** [comment]
I don't see this error anymore, but a different one that might be related. It happens when one tries to fit a compound model. It doesn't happen when we fit a single model. The error is in line 333 in viewer.py. When 'model' is a CompoundModel instance, get_model_item returns None.

I guess it's a related error because the calling stack goes thru that 'emit' call used when updating a model.

**Comment by nmearl** [comment]
Try now with 3a2ae6535814fcc98ef27f0aa9de6ae9fb0f0af6.

**Comment by ibusko** [comment]
It works now!
