### ISSUE TITLE
Needs clarification on layers and ROI

### ISSUE THREAD

**Issue by pllim** [nmearl/specviz#59]
When I select a ROI, I see two layers. Intuitively, the first one would be the original data, and the second one is the one with ROI. But when I select the first one, the plot blurs out the regions outside the ROI (as shown) but does not blur out anything when I select the second layer. What is the logic behind this behavior?

![untitled](https://cloud.githubusercontent.com/assets/2090236/13091414/07ae4516-d4c9-11e5-9116-1fa2f3738171.png)

**Comment by nmearl** [comment]
I think you might need to pull from master again. The intended behavior is that the selected layer will show its data plus its errors (if you zoom in, you can see the error bars). Any non-selected layers should show just its data.

<img width="1392" alt="screen shot 2016-02-16 at 4 47 15 pm" src="https://cloud.githubusercontent.com/assets/4141126/13092282/0f354c36-d4cd-11e5-93f9-673c90bdad0c.png">

**Comment by pllim** [comment]
I have been using the master. Could this be another Linux vs Mac thing?

**Comment by pllim** [comment]
@nmearl , was your screenshot generated with the latest master? Just making sure we're both on the same page.

**Comment by nmearl** [comment]
It's a branch off the latest master. But it includes a commit I pushed about 3 hours again (6a97bbeac978d02f7e09f36192d0c94c2d47d672) that solved a bug with this precise issue.

**Comment by pllim** [comment]
I already picked up that change. But I am wondering if I introduced another bug in my commits today. I had to default errors to zeros (instead of None) in loader in order to fix #46 (the test data from Harry did not have uncertainty column). See my changes to `pyfocal/interfaces/loaders.py` in #51. That's why I am wondering if you are also using the latest master, since apparently you are unaffected.

**Comment by nmearl** [comment]
Are you still seeing this issue?

**Comment by pllim** [comment]
Actually, not anymore. And since no one else complained about it, must be just me.
